# Generated by Django 3.2.20 on 2023-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfiedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='satisfied_customer_images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
