# Generated by Django 3.2.20 on 2023-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfiedcustomer',
            name='active_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='satisfiedcustomer',
            name='customer_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
