# Generated by Django 3.2.20 on 2023-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230822_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfiedcustomer',
            name='customer_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='satisfiedcustomer',
            name='image',
            field=models.ImageField(upload_to='satisfied_customer_images'),
        ),
    ]
