# Generated by Django 3.2.20 on 2023-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_satisfiedcustomer_customer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('active_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
