# Generated by Django 3.2.20 on 2023-09-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_login_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
