# Generated by Django 3.2.20 on 2023-11-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
