# Generated by Django 3.2.20 on 2023-08-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcategory_add_to_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category Name', 'verbose_name_plural': 'Category Names'},
        ),
    ]
