# Generated by Django 3.2.20 on 2023-08-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Name', 'verbose_name_plural': 'Names'},
        ),
    ]
