# Generated by Django 3.2.20 on 2023-08-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product Name', 'verbose_name_plural': 'Product Names'},
        ),
    ]
