# Generated by Django 3.2.20 on 2023-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='active'),
        ),
    ]
