# Generated by Django 3.2.20 on 2023-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='addtime'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='category_image'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='category_name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
