# Generated by Django 3.2.20 on 2023-08-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230811_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_home',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='add_to_home'),
        ),
        migrations.AddField(
            model_name='product',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='addtime'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount_percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='out_of_stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory', verbose_name='product_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='product_image'),
        ),
    ]
