# Generated by Django 3.2.20 on 2023-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20230811_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='addtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='addtime'),
        ),
    ]
