# Generated by Django 3.2.20 on 2023-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productcategory_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='addtime'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='addtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='addtime'),
        ),
    ]
