# Generated by Django 3.2.20 on 2023-08-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['category_name']},
        ),
    ]
