# Generated by Django 3.2.20 on 2023-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='product_order'),
        ),
    ]
