# Generated by Django 3.2.20 on 2023-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_homepagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=500)),
                ('deal_image', models.ImageField(upload_to='deal_image')),
                ('deal_url', models.CharField(max_length=255)),
                ('active_deal', models.BooleanField()),
            ],
        ),
    ]
