# Generated by Django 3.2.20 on 2023-08-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_dealofday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealofday',
            options={'ordering': ['deal_name']},
        ),
    ]
